const bcrypt = require('bcryptjs');

// High-fidelity in-memory store ensuring 100% zero-friction out-of-the-box experience
class MemoryStore {
  constructor() {
    this.users = [];
    this.connections = [];
    this.messages = [];
    this.studySessions = [];
    this.studyGroups = [];
    this.notifications = [];
    this.initialized = false;
  }

  async init() {
    if (this.initialized) return;

    const hashedPassword = await bcrypt.hash('password123', 10);

    // Initial student profiles matching requirements #29 & #1
    this.users = [
      {
        _id: 'usr_arun_101',
        name: 'Arun Kumar',
        email: 'arun@college.edu',
        password: hashedPassword,
        college: 'National Institute of Technology (NIT)',
        course: 'Computer Science & Engineering',
        year: '3rd Year',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
        bio: 'Java enthusiast & LeetCode grinder. Currently diving deep into Distributed Systems and System Design. Ready to mentor anyone starting DSA or Java!',
        subjectsToLearn: ['Web Development', 'System Design', 'Cloud Computing'],
        subjectsToTeach: ['Java', 'Data Structures', 'DBMS'],
        skillLevel: 'Intermediate',
        learningStyle: 'Practical',
        learningPace: 'Moderate',
        availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        availableTimeSlots: ['Evening (5 PM - 9 PM)', 'Night (9 PM - 12 AM)'],
        interests: ['Competitive Programming', 'Open Source', 'Hackathons'],
        isOnline: true,
        lastActive: new Date(),
        createdAt: new Date('2026-09-01'),
      },
      {
        _id: 'usr_rahul_102',
        name: 'Rahul Verma',
        email: 'rahul@college.edu',
        password: hashedPassword,
        college: 'Indian Institute of Information Technology (IIIT)',
        course: 'Information Technology',
        year: '2nd Year',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
        bio: 'Machine Learning & Python fanatic. Building neural networks and studying probability theory. Looking for a study buddy to keep each other accountable.',
        subjectsToLearn: ['Data Structures', 'Database', 'Computer Networks'],
        subjectsToTeach: ['Python', 'Machine Learning', 'Mathematics'],
        skillLevel: 'Intermediate',
        learningStyle: 'Visual',
        learningPace: 'Moderate',
        availableDays: ['Tuesday', 'Thursday', 'Saturday', 'Sunday'],
        availableTimeSlots: ['Afternoon (12 PM - 5 PM)', 'Evening (5 PM - 9 PM)'],
        interests: ['Deep Learning', 'Kaggle', 'Math Puzzles'],
        isOnline: true,
        lastActive: new Date(),
        createdAt: new Date('2026-09-02'),
      },
      {
        _id: 'usr_priya_103',
        name: 'Priya Sharma',
        email: 'priya@college.edu',
        password: hashedPassword,
        college: 'Delhi Technological University (DTU)',
        course: 'Software Engineering',
        year: '3rd Year',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
        bio: 'Full Stack MERN developer and SQL fan. Building clean interactive web apps. Looking for peer practice on advanced algorithm problem solving.',
        subjectsToLearn: ['Data Structures', 'Operating Systems', 'Machine Learning'],
        subjectsToTeach: ['Web Development', 'Database', 'Programming'],
        skillLevel: 'Advanced',
        learningStyle: 'Problem Solving',
        learningPace: 'Fast',
        availableDays: ['Monday', 'Wednesday', 'Thursday', 'Sunday'],
        availableTimeSlots: ['Evening (5 PM - 9 PM)', 'Night (9 PM - 12 AM)'],
        interests: ['React.js', 'UI/UX Design', 'Web3'],
        isOnline: true,
        lastActive: new Date(),
        createdAt: new Date('2026-09-03'),
      },
      {
        _id: 'usr_karthik_104',
        name: 'Karthik Nair',
        email: 'karthik@college.edu',
        password: hashedPassword,
        college: 'BITS Pilani',
        course: 'Computer Science',
        year: '4th Year',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
        bio: 'Competitive programmer (Codeforces Candidate Master) in C++. Happy to teach algorithms, dynamic programming, and graphs to dedicated peers.',
        subjectsToLearn: ['Machine Learning', 'Computer Networks'],
        subjectsToTeach: ['Data Structures', 'Programming', 'Mathematics'],
        skillLevel: 'Advanced',
        learningStyle: 'Problem Solving',
        learningPace: 'Fast',
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
        availableTimeSlots: ['Night (9 PM - 12 AM)'],
        interests: ['Algorithms', 'Math Olympiad', 'Linux Kernel'],
        isOnline: false,
        lastActive: new Date(Date.now() - 3600000),
        createdAt: new Date('2026-09-04'),
      },
      {
        _id: 'usr_ananya_105',
        name: 'Ananya Patel',
        email: 'ananya@college.edu',
        password: hashedPassword,
        college: 'Vellore Institute of Technology (VIT)',
        course: 'Data Science & Artificial Intelligence',
        year: '2nd Year',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        bio: 'Mathematics enthusiast who loves translating mathematical formulas into clean Python code. Enjoy collaborative whiteboard sessions and group reviews.',
        subjectsToLearn: ['Data Structures', 'Web Development', 'Operating Systems'],
        subjectsToTeach: ['Mathematics', 'Python', 'Machine Learning'],
        skillLevel: 'Intermediate',
        learningStyle: 'Discussion',
        learningPace: 'Moderate',
        availableDays: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
        availableTimeSlots: ['Morning (8 AM - 12 PM)', 'Evening (5 PM - 9 PM)'],
        interests: ['Linear Algebra', 'Data Viz', 'Badminton'],
        isOnline: true,
        lastActive: new Date(),
        createdAt: new Date('2026-09-05'),
      },
      {
        _id: 'usr_devanshi_106',
        name: 'Devanshi Joshi',
        email: 'devanshi@college.edu',
        password: hashedPassword,
        college: 'College of Engineering Pune (COEP)',
        course: 'Computer Technology',
        year: '3rd Year',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
        bio: 'Cloud & DevOps explorer (Docker, Kubernetes, AWS). Looking for study mates for Computer Networks and Operating Systems theory exams.',
        subjectsToLearn: ['Computer Networks', 'Operating Systems', 'Database'],
        subjectsToTeach: ['Programming', 'Web Development'],
        skillLevel: 'Intermediate',
        learningStyle: 'Visual',
        learningPace: 'Moderate',
        availableDays: ['Tuesday', 'Thursday', 'Saturday'],
        availableTimeSlots: ['Afternoon (12 PM - 5 PM)', 'Evening (5 PM - 9 PM)'],
        interests: ['Cloud Architecture', 'Linux', 'Microservices'],
        isOnline: false,
        lastActive: new Date(Date.now() - 7200000),
        createdAt: new Date('2026-09-06'),
      },
      {
        _id: 'usr_rohit_107',
        name: 'Rohit Singh',
        email: 'rohit@college.edu',
        password: hashedPassword,
        college: 'Manipal Institute of Technology (MIT)',
        course: 'Information Science',
        year: '1st Year',
        avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
        bio: 'Eager freshman ready to learn fundamentals of programming, C/C++, and discrete math. Looking for patient study buddies to work on homework and lab assignments.',
        subjectsToLearn: ['Programming', 'Data Structures', 'Mathematics', 'Web Development'],
        subjectsToTeach: ['Programming'],
        skillLevel: 'Beginner',
        learningStyle: 'Practical',
        learningPace: 'Slow',
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        availableTimeSlots: ['Evening (5 PM - 9 PM)'],
        interests: ['Robotics', 'C Programming', 'Tech Podcasts'],
        isOnline: true,
        lastActive: new Date(),
        createdAt: new Date('2026-09-07'),
      },
    ];

    // Seed Connections
    this.connections = [
      {
        _id: 'conn_1',
        requester: 'usr_arun_101',
        recipient: 'usr_rahul_102',
        status: 'accepted',
        notes: 'Would love to study Python and exchange Java concepts!',
        createdAt: new Date('2026-09-10'),
      },
      {
        _id: 'conn_2',
        requester: 'usr_priya_103',
        recipient: 'usr_arun_101',
        status: 'accepted',
        notes: 'Hey Arun, saw you are grinding DSA LeetCode. Let us solve together!',
        createdAt: new Date('2026-09-12'),
      },
      {
        _id: 'conn_3',
        requester: 'usr_ananya_105',
        recipient: 'usr_arun_101',
        status: 'pending',
        notes: 'Hi Arun! Want to connect for upcoming DBMS and DSA prep.',
        createdAt: new Date('2026-09-28'),
      },
      {
        _id: 'conn_4',
        requester: 'usr_rohit_107',
        recipient: 'usr_arun_101',
        status: 'pending',
        notes: 'Senior, could you please mentor me in basic Java and array problems?',
        createdAt: new Date('2026-09-29'),
      },
    ];

    // Seed Messages
    this.messages = [
      {
        _id: 'msg_1',
        sender: 'usr_arun_101',
        recipient: 'usr_rahul_102',
        content: 'Hey Rahul! Are you available to study Java & Python algorithms today?',
        read: true,
        createdAt: new Date(Date.now() - 3600000 * 4),
      },
      {
        _id: 'msg_2',
        sender: 'usr_rahul_102',
        recipient: 'usr_arun_101',
        content: "Yes! I'm completely free after 6 PM. Shall we schedule a 1-hour session?",
        read: true,
        createdAt: new Date(Date.now() - 3600000 * 3),
      },
      {
        _id: 'msg_3',
        sender: 'usr_arun_101',
        recipient: 'usr_rahul_102',
        content: "Sounds great! I just scheduled our 'Java & Python Algo Session' on the portal for 6:00 PM.",
        read: true,
        createdAt: new Date(Date.now() - 3600000 * 2),
      },
      {
        _id: 'msg_4',
        sender: 'usr_rahul_102',
        recipient: 'usr_arun_101',
        content: 'Awesome! See you in the study room at 6 PM. Looking forward to it!',
        read: false,
        createdAt: new Date(Date.now() - 1800000),
      },
      {
        _id: 'msg_5',
        sender: 'usr_priya_103',
        recipient: 'usr_arun_101',
        content: 'Hey Arun, did you check the new binary tree problem set?',
        read: true,
        createdAt: new Date(Date.now() - 86400000),
      },
    ];

    // Seed Study Groups
    this.studyGroups = [
      {
        _id: 'grp_1',
        name: 'Java Beginners Cohort',
        subject: 'Java',
        description: 'A friendly community for learning object-oriented programming, core Java, and practical coding exercises.',
        skillLevel: 'Beginner',
        creator: 'usr_arun_101',
        members: ['usr_arun_101', 'usr_rohit_107', 'usr_rahul_102'],
        avatar: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=400&q=80',
        maxMembers: 50,
        memberCount: 32,
        tags: ['Java', 'OOP', 'Beginners'],
        createdAt: new Date('2026-09-01'),
      },
      {
        _id: 'grp_2',
        name: 'DSA Preparation Squad',
        subject: 'Data Structures',
        description: 'Daily LeetCode discussions, dynamic programming breakdowns, mock technical interview sessions.',
        skillLevel: 'Intermediate',
        creator: 'usr_karthik_104',
        members: ['usr_karthik_104', 'usr_arun_101', 'usr_priya_103'],
        avatar: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=400&q=80',
        maxMembers: 60,
        memberCount: 48,
        tags: ['LeetCode', 'DSA', 'Algorithms'],
        createdAt: new Date('2026-09-03'),
      },
      {
        _id: 'grp_3',
        name: 'Machine Learning Study Group',
        subject: 'Machine Learning',
        description: 'Exploring neural networks, PyTorch, mathematical modeling, and participating in Kaggle student challenges.',
        skillLevel: 'Intermediate',
        creator: 'usr_rahul_102',
        members: ['usr_rahul_102', 'usr_ananya_105'],
        avatar: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&w=400&q=80',
        maxMembers: 40,
        memberCount: 25,
        tags: ['AI', 'Python', 'Kaggle'],
        createdAt: new Date('2026-09-05'),
      },
      {
        _id: 'grp_4',
        name: 'Full-Stack Web Dev Hub',
        subject: 'Web Development',
        description: 'Building modern responsive web apps with React, Node, Tailwind, and REST APIs. Code reviews and project showcases.',
        skillLevel: 'All Levels',
        creator: 'usr_priya_103',
        members: ['usr_priya_103', 'usr_arun_101', 'usr_devanshi_106'],
        avatar: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=400&q=80',
        maxMembers: 50,
        memberCount: 38,
        tags: ['React', 'NodeJS', 'FullStack'],
        createdAt: new Date('2026-09-08'),
      },
    ];

    // Seed Study Sessions
    this.studySessions = [
      {
        _id: 'ses_1',
        title: 'Java Practice & DSA Trees Session',
        subject: 'Java',
        date: new Date().toISOString().split('T')[0],
        time: '18:00',
        duration: 60,
        description: 'Reviewing Binary Search Trees, traversal algorithms, and implementing BST insertion in Java.',
        createdBy: 'usr_arun_101',
        partner: 'usr_rahul_102',
        status: 'upcoming',
        meetingLink: 'https://vibemates.study/room/dsa-trees-practice',
        notes: 'Bring questions on recursive vs iterative tree traversals.',
        createdAt: new Date(),
      },
      {
        _id: 'ses_2',
        title: 'DBMS SQL & Indexing Deep Dive',
        subject: 'Database',
        date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
        time: '19:30',
        duration: 90,
        description: 'Covering B-Tree indexes, query optimization, and normal forms (3NF & BCNF).',
        createdBy: 'usr_priya_103',
        partner: 'usr_arun_101',
        status: 'upcoming',
        meetingLink: 'https://vibemates.study/room/dbms-indexing',
        notes: 'We will practice 5 LeetCode SQL hard problems.',
        createdAt: new Date(),
      },
      {
        _id: 'ses_3',
        title: 'Machine Learning Gradient Descent Lab',
        subject: 'Machine Learning',
        date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
        time: '17:00',
        duration: 60,
        description: 'Deriving gradient descent cost function on whiteboards and coding it in pure NumPy.',
        createdBy: 'usr_rahul_102',
        partner: 'usr_arun_101',
        status: 'completed',
        meetingLink: 'https://vibemates.study/room/ml-grad-descent',
        notes: 'Completed successfully! Next session will cover backpropagation.',
        createdAt: new Date(Date.now() - 86400000 * 3),
      },
    ];

    // Seed Notifications
    this.notifications = [
      {
        _id: 'notif_1',
        recipient: 'usr_arun_101',
        sender: 'usr_ananya_105',
        type: 'connection_request',
        title: 'New Connection Request',
        message: 'Ananya Patel sent you a study connection request for DBMS & DSA.',
        link: '/connections',
        read: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 30),
      },
      {
        _id: 'notif_2',
        recipient: 'usr_arun_101',
        sender: 'usr_rahul_102',
        type: 'new_message',
        title: 'New Message from Rahul',
        message: 'Awesome! See you in the study room at 6 PM. Looking forward to it!',
        link: '/chat',
        read: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 15),
      },
      {
        _id: 'notif_3',
        recipient: 'usr_arun_101',
        sender: 'usr_priya_103',
        type: 'connection_accepted',
        title: 'Connection Accepted 🎉',
        message: 'Priya Sharma accepted your connection request. You are now VibeMates!',
        link: '/chat',
        read: true,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      },
      {
        _id: 'notif_4',
        recipient: 'usr_arun_101',
        sender: 'usr_karthik_104',
        type: 'mate_matched',
        title: 'High Compatibility Mate Found! 🎯',
        message: 'Karthik Nair shares 92% compatibility with your learning goals in C++ & DSA.',
        link: '/find-mates',
        read: true,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
      },
    ];

    this.initialized = true;
  }
}

const memoryStore = new MemoryStore();

module.exports = memoryStore;
